site_name: LeafLux Documentation

theme:
  name: material
  features:
    - content.code.copy

nav:
  - Home: index.md
  - How To Guides: how-to-guides.md
  - Troubleshooting: troubleshooting.md
  - Reference: reference.md

plugins:
  - mkdocstrings:
      handlers:
        python:
          paths: [.]
          options:
            docstring_style: numpy
            docstring_section_style: table
            show_root_heading: true
            show_source: false
            members_order: source
            annotations_path: brief
            separate_signature: true
            show_signature_annotations: true
            docstring_options:
              ignore_init_summary: true
