site_name: LeafLux Documentation

theme:
  name: material
  features:
    - content.code.copy

nav:
  - Home: index.md
  - How To Guides: how-to-guides.md
  - Reference: reference.md
  - Troubleshooting: troubleshooting.md

plugins:
  - mkdocstrings

# markdown_extensions:
#   - admonition
#   - codehilite
#   - toc:
#       permalink: true

plugins:
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: numpy
            docstring_section_style: table
            ignore_init_summary: true
            show_root_heading: true
            show_source: false
            members_order: source
            annotations_path: brief
            separate_signature: true
            show_signature_annotations: true
