name: build mkdocs

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
          python-version: 3.12
          cache: pip
      - run: pip install mkdocs mkdocstrings mkdocstrings-python mkdocs-material black
      - run: mkdocs gh-deploy --force --clean --verbose